### ISSUE TITLE
Enforcing User Behavior

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#174]
How much will we be enforcing good behavior on the part of the user? This issue is a place where you can list opportunities we have for such enforcement.

- Will we disallow changes to the Risk Limit set originally by the Secretary of State? In other words, does the RLA Tool stop the SoS from logging in halfway through the audit to change the Risk Limit?

- What if ID and Ballot Style on Ballot Verification screen match the ID and Ballot Style on the paper ballot, but the contests on the screen do not match the contests on the paper ballot. What would we expect Audit Board users to do in this instance? Of course, if the meaning of the Ballot Styles is strictly enforced both in the Tool and on paper, this case will never arise.

Clicking the browser "back" arrow from the Ballot Review screen of the Audit section does not go back to the Ballot Verification screen. Instead, that action brings the system back to the "Hello, Acme County" screen. How can we prevent users from taking this bad, bad action?

**Comment by nealmcb** [comment]
The most important aspect of this is to maintain an immutable audit log of actions, so that an "audit of the audit" can be used later to evaluate the actual sequence of actions.

The latest draft rule still allows the SoS to change Rule 25 at any time:

> 25.2.4 FOR THE 2017 COORDINATED ELECTION, THE SECRETARY OF STATE MAY, BY ORDER ALTER ANY OF THE REQUIREMENTS OUTLINED IN RULE 25.2.

So I think we should not enforce anything unless there is some other specific requirement to enforce it. In particular, changing the risk limit should only be prohibited if it truly doesn't make sense in any way, and would cause the tool to malfunction.

In terms of the contests seen on the paper not matching the contests seen on the ballot, that is an explicit piece of evidence the tool is designed to uncover and document. If the auditors don't see a contest that they're told to enter, they should be able to indicate that fact, and they should also be able to say "we see this contest on the paper" even if it is not on the entry screen, in such a way that the appropriate discrepancy is entered.

**Comment by kiniry** [comment]
In situations where there is underspecification, I am enforcing a particular ordering on actions in the ASMs that will be exposed via the UI/UX.  All is in alignment with the Statutes and draft Rules.  As such, at the moment, risk limits are not mutable after they are set.

**Comment by kiniry** [comment]
I am labeling this with `cdos` to get their input.

**Comment by sfsinger19103** [comment]
I am closing this issue because the particular user behaviro questions have been addressed and the back button issue has been separated out into issue #527.
