### ISSUE TITLE
SoS functionality missing

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#183]
SoS needs functionality that is not yet visible in master front end: 

- input of risk limits, 

- input of random seed

- choice of contests to drive sample sizes, 

- declaring that a contest must move to a hand count

**Comment by nealmcb** [comment]
Some of this is actually in the SoS functionality since deliverable 1.1. As noted in the README.md in deliverable 1.1, until the back-end is hooked up to drive the front end, you should go to the menu in the upper left, and select "Audit" to get started, and see a place to enter risk limits and random seed, and a bit more.

**Comment by ranweiler** [comment]
Except for the full hand count declaration, this is done. I've opened #247 to capture that, so I'm closing out this issue.
