### ISSUE TITLE
split authentication out into a separate ASM

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#213]
Component ASMs in our specification relate to different UIs in the tool.  As such, the first authentication state and transitions should be in a trivial authentication ASM.

**Comment by dmzimmerman** [comment]
This may not be quite as trivial as one might think, since authentication is likely going to be a multi-step process... and moreover, we'll probably need a new authentication ASM for every authentication that is attempted. I suppose we can do something like create the ASM with the first authentication step, return some kind of reference to it in the HTTP response, and have that sent with subsequent authentication steps... as well as some kind of garbage collection/timeout on old ASMs that don't get completed.

**Comment by kiniry** [comment]
Has this been completed in #245, @dmzimmerman?

**Comment by dmzimmerman** [comment]
It’s removed from the other ASMs. It does not have its own because right now it’s so simple it doesn’t really need one - a session is either authenticated or not, and can be authenticated to a different admin at any time. Which reminds me that we probably want to have an `unauthenticate` endpoint of some sort, though passing bad credentials to the `authenticate` ones has that effect now.

**Comment by kiniry** [comment]
I think that design is appropriate for now, especially given our lack of knowledge about their two-factor authentication system as of now.  

I'm closing this issue for now and we can re-open it if/when appropriate.

I'll file a separate issue on the /unauthenticate endpoint.
