### ISSUE TITLE
drop in clearer statement about no license for use yet

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#315]

**Comment by kiniry** [comment]
Fixed in #315.

**Comment by cjerdonek** [comment]
Suggestion: it would help if the file name were changed to `LICENSE.md`. Currently, GitHub doesn't recognize the file as markdown and so the hyperlinks aren't clickable, etc.

**Comment by cjerdonek** [comment]
A couple additional, unrelated comments:

The LICENSE file tells readers to add comments to this issue to provide input on licensing, but this issue is marked "closed," and the title of this issue isn't really consistent. Would it be better to create a new open issue titled something like, "[Discussion] Add open source license," and then have the LICENSE file link to that for comments?

Second, I notice that this project [has Facebook's React library as a dependency](https://github.com/FreeAndFair/ColoradoRLA/blob/c4e64b01ce61ec738b34efe4c8eb5a719b8696e7/client/package.json#L42). The "viral" implications of using React because of its restrictive [`PATENTS`](https://github.com/facebook/react/blob/master/PATENTS) file has gained more visibility recently (e.g. see [here](https://news.ycombinator.com/item?id=14779881) for a recent discussion on Hacker News). IANAL, but it seems these restriction would extend to users of this project. By using the library, the user would give up the ability to exercise any of its patent rights against Facebook or its affiliates (on any topic, not just related to React, which is why the requirement is so controversial).

The Apache Foundation [recently disallowed](https://issues.apache.org/jira/browse/LEGAL-303?focusedCommentId=16088663&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16088663) (link from HN discussion above) its projects from using React and similarly licensed+patents projects. And in the temporary transition period, AF is requiring its projects to notify its users that the dependency exists: "you MUST ensure that NOTICE explicitly notifies the end-user that a Facebook BSD+patents licensed artifact exists. They may not be aware of it up to now, and that MUST be addressed."

**Comment by nealmcb** [comment]
Thanks for the links, @cjerdonek.
@ranweiler @kiniry There has been a lot of news and discussion since we last discussed this. Here is a very recent sttement from Facebook: [Explaining React's license | Engineering Blog | Facebook Code](https://code.facebook.com/posts/112130496157735/explaining-react-s-license/)

**Comment by kiniry** [comment]
Good point wrt the discussion issue @cjerdonek.  I have filed #452 as a consequence and updated `LICENSE.md`.

**Comment by kiniry** [comment]
We had our lawyer explicitly review React wrt Colorado's choice of GPLv3.  She stated at the time (17 July) that she saw no issue with our using it.  I'll forward your comments above to her for additional review.

**Comment by cjerdonek** [comment]
Perfect. Thanks, @kiniry!

**Comment by cjerdonek** [comment]
FYI, good news. Facebook announced that they will be relicensing React under MIT:
https://code.facebook.com/posts/300798627056246

More discussion: https://news.ycombinator.com/item?id=15316175
