### ISSUE TITLE
can the audit board members change mid-audit?

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#378]
Currently we only permit audit board members to sign in once.  If they logout and start auditing again, it presumes the same audit board members are present.  Can audit board members change mid-audit?

**Comment by sfsinger19103** [comment]
I'm pretty sure that CDOS wants to allow changes in audit board members mid-audit. I can't find documentation, though.

**Comment by sfsinger19103** [comment]
Per CDOS email from Dwight Shellman 8/28:

2.    How should multiple audit board sign-ins be treated?
If audit board members sign out (say, before lunch) and then sign back in (say, after lunch), the RLA Tool should "present the same blank sign-in screen that it would present at the very beginning of the audit."

**Comment by ranweiler** [comment]
Fixed in #508. The user can now explicitly sign out of the audit board. Note that this is _distinct_ from the user "logging out" of the app. If the user logs out, the current audit board is _not_ automatically "signed out". If desired, we can make "user logout" also trigger an "audit board sign-out".
