### ISSUE TITLE
Different contests with same name

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#521]
per CDOS feedback 8/28

The contests from the counties are included under 1 list. How do we differentiate contests from different counties that have the same contest name (e.g., “County Commissioner – District 1”)? Are they assigned the same ID or are they assigned different IDs? Can the contests be sorted by county to make it easier to choose local county contests?

**Comment by dmzimmerman** [comment]
The contests can be sorted by county if the client feels like doing that; it has enough information. It's not clear to me why anybody using the client cares what IDs contests are assigned, but in this case, they are assigned the same ID - we have been operating under the assumption that contests had unique names, because otherwise we would (eventually) have no way of distinguishing between single-county and multi-county contests. However, they are tallied and audited separately, at the county level, for the moment, because auditing for multi-county contests is still undefined.

**Comment by nealmcb** [comment]
For the November 2017 election, the state should not select any contest to drive the RLA if it is a multi-county contest, since we don't have an implementation of the techniques, such as a Bayes audit, that would let us calculate sample sizes or risk levels for that sort of sample stratified across counties.
It would help if the tool can identify such multi-county contests (relying on the name being unique per contest, across counties), and exclude them as options during contest selection.
In addition, I agree that sorting contests by county would be helpful in making at least one selection per county.

**Comment by dmzimmerman** [comment]
The tool could identify such contests easily, though it might be mistaken, given the question they asked above.

**Comment by sfsinger19103** [comment]
If I understand correctly, in order to address their concern we need to abandon our assumption that contest names are unique. Are we on track to abandon that assumption and make the necessary changes?

**Comment by sfsinger19103** [comment]
Per NealMcB: 

> There are always multi-county contests, e.g. school boards. Confirmed with the counties a few weeks ago.

**Comment by dmzimmerman** [comment]
Contests are now stored with county IDs in the database. If they want to somehow "link" contests together across counties, they have to come up with some way to do that that augments the data we currently get from the CVR files. Which won't happen this year. So I'm closing this.
