### ISSUE TITLE
Remove/redefine "remaining to audit" column from County/Contest Updates

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#531]
From CDOS 8/28 feedback (see screenshots in [Word file](https://github.com/FreeAndFair/ColoradoRLA/files/1259027/RLA.Tool.Feedback.08.28.2017.docx))

We need to clarify with CDOS whether they want that column and, if so, what they want in it. If a count of ballot cards, how do they want to deal with cards audited more than once? Note that random selection is with replacement, not without replacement.

**Comment by nealmcb** [comment]
This column is very useful for tracking progress. But the numbers would ideally only be reported for single-county contests, since we aren't implementing the significantly-more-complex algorithms and procedures to audit multi-county contests as part of this contract. Only single-county contests should be selected to drive the RLA.

The numbers may also be confusing for contests with very few ballots (compared to the estimated number remaining to audit). That is because selection is done "with replacement", and any ballot card may be selected multiple times.  Each of those selections is counted in the estimate, even though the county only needs to audit a given ballot card once.
It would slow the system to give precise estimates taking into account how selecting a single ballot checks off multiple selections.

It would help to point to a clarification of these sorts of confusion in the popup help text.

**Comment by sfsinger19103** [comment]
Per 8/29 conversation, CDOS does not want the Stark sample size estimate information currently in that column.

**Comment by ranweiler** [comment]
@sfsinger19103 would you please restate exactly what is supposed to happen here? Are we completely removing, without replacement, the estimated ballots to audit from both the contest updates and the county updates?

**Comment by sfsinger19103** [comment]
Current columns for County Update are:

Name | Status | Submitted | Discrepancies | Disagreements | Remaining to Audit

Change these names to (changes in bold):
Name | Status | Submitted | Discrepancies | Disagreements | Remaining in **Round | Est. Remaining Ballots**

Values for "Remaining in Round" column are something we did not provide in phase-2, something based on the number of CVRs already interpreted by audit board and total number of CVRs in the round (I'm not sure how to handle dupes).

Values for "Est. Remaining Ballots" (CDOS language) are the same as the Phase-2 "Remaining to Audit" column.

**Comment by sfsinger19103** [comment]
For Contest Update, the current columns are:

ID | Name | Audit Status | Target Risk Limit | Remaining to Audit

Change these to:
**County** | Name | Audit Status | Target Risk Limit 

It's conceivable that CDOS will want a "Remaining in Round" column on this table also, but that info is in the County Update table and won't vary by contest within a County.

Values for "Remaining in Round

**Comment by ranweiler** [comment]
Thank you @sfsinger19103, that is _very_ helpful!

**Comment by ranweiler** [comment]
Closed in #558.
