### ISSUE TITLE
Include storage location in CVR endpoint

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#587]
In the response for the `/cvr-to-audit-list` endpoint, each returned ballot includes a `storage_location` field. In the `/cvr/id/{id}` endpoint, it does not. Include the `storage_location` field in the second endpoint so we can render it on the ballot verification page, when it has a value on the preceding page.

Needed for #571.

**Comment by kiniry** [comment]
Election official would/should have already retrieved the ballot and it doesn’t matter to the audit board which bin it came from, so this is UI polish we can move to the next milestone.

**Comment by dmzimmerman** [comment]
Moreover, there are good technical reasons why we probably should not do another database query for the location every time the client asks for a CVR by ID.

**Comment by dmzimmerman** [comment]
Unless it is absolutely essential, this is not going to be implemented. The location is not part of the cast vote record, and is therefore not returned when the cast vote record is retrieved; however, it _is_ part of the information required to gather ballots to audit, and that's why it's available from the `/cvrs-to-audit` endpoint (which really, to be honest, should be named `/ballots-to-audit` but for some reason I didn't do that in the first place).

**Comment by ranweiler** [comment]
We've changed how do things on the client to make this unnecessary.
