### ISSUE TITLE
Clarify spec for random seed entry (follow Rule 25? or Starks' tool? or something else?)

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#625]
A seed of only 6 digits was entered, which generated the message "Please verify that the seed is a numeral at least 20 digits long". Dr. Stark’s tool was able to handle a seed up to 20 digits (20 digits maximum), so why is 20 the minimum for the RLA tool?

I interpret this as a request to allow any integer up to 10^20-1. I'll confirm with CDOS.

**Comment by dmzimmerman** [comment]
Their rule explicitly says "at least 20 digits", so unless they're rewriting their own rule, this is not something that's reasonable for us to do.

**Comment by sfsinger19103** [comment]
I'll ask them, but CDOS is our client, not the law.

And there is an equivalence between strings of exactly 20 digits and integers n with 
0 <= n <= 10^20 - 1.

**Comment by dmzimmerman** [comment]
The random seeds are not numbers; they're strings.

**Comment by sfsinger19103** [comment]
Yes, indeed they are. Are you suggesting that we deny our client their desired shortcut for entry of strings of 20 digits? I think we should cheerfully add those leading zeroes to whatever they enter.

**Comment by dmzimmerman** [comment]
Oh? OK. How many of them? How do we know they didn't mean 21 "0"s, or 19, instead of 20? What if they _enter_ 21 0s, do we shorten it to 20? What if they enter 21 1s? 

But whatever. Let them actually _tell_ us what they want, and then complain; since they never told us, we made the quite reasonable assumption that they would want what they wrote in their rules. If we _limit_ them to 20 digits, we are explicitly _preventing_ them from doing what their rules say, so that seems infeasible. If we _don't_ limit them to 20 digits, we have no principled way to derive a seed from whatever they enter.

**Comment by dmzimmerman** [comment]
Your "interpretation", above, is exactly the kind of fuzziness that causes this sort of situation in the first place. So yes, maybe in the future get a clarification before filing this sort of issue.

**Comment by sfsinger19103** [comment]
My interpretation isn't fuzzy. It was based on the assumption that they needed a string of exactly 20 digits -- which, as you just pointed out, is not what Rule 25 says.

**Comment by dmzimmerman** [comment]
And is also not what our tool enforces.

**Comment by sfsinger19103** [comment]
Asked CDOS by email whether they want to change the spec for the random seed from the spec in Rule 25 to something else.

**Comment by sfsinger19103** [comment]
Per 9/5 conversation with CDOS, leave this as it was in 1.0.0 alpha 1 -- i.e., follow Rule 25.
