### ISSUE TITLE
Allow County to print list of paper ballots to look for

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#628]
A Print or Export button should be provided to allow the county to have a paper list of the paper ballots to look for.

I added server label because this is a new endpoint for creating this new report, right? If not, take off the label.

**Comment by dmzimmerman** [comment]
They can just print their browser window, of course. If they really want a separate, printable file, that's a new endpoint, yes.

**Comment by sfsinger19103** [comment]
Here's what CDOS wrote: " A Print or Export button should be provided to allow the county to have a paper list of the paper ballots to look for." That doesn't sound like printing the browser window.

**Comment by nealmcb** [comment]
As noted at #618, the counties want the capability to sort their ballots either by location or by random selection sequence number, in this case via a downloaded CSV file.

See a spec for what the download should contain at #125. Adding a "round number" probably also makes sense for this download case, so that the download can include future selections that may be needed in case of escalation.

If some audit tool export doesn't include the random selection sequence number (i.e., "1" for the first ballot selected in the first round), neither the counties nor the state nor the public will be able to verify in a straightforward way that the random selection is correct, given the CVRs and the seed. They would be able to confirm that each round had the right set of selections, but not know e.g. which to pull next if they want to be proactive.

**Comment by dmzimmerman** [comment]
A "Print" button sounds _exactly_ like printing the browser window, @sfsinger19103. An "Export" button, not as much. The information they get does include the random selection sequence number (though it is currently indexed from 0 - this could be changed server-side but might make life difficult for the client, and is more easily changed client-side by bumping up the numbers by 1 before display, or by doing so if we generate a dedicated CSV or Excel file for them). Adding a round number will not happen, as no calculations are done for future rounds until the end of a round.

**Comment by sfsinger19103** [comment]
CDOS 9/11:
We are not sure software licenses will permit it, but it would be great if the tool could generate parallel columns of ballot identifiers that counties can print on an Avery label template.  E.g., Avery Label 5261, the Word template for which is attached.

**Comment by dmzimmerman** [comment]
Unless this can be done in-browser by the client using the data it already has, this is probably not happening for this initial contract; we definitely don't have the ability to easily generate Word files.

**Comment by sfsinger19103** [comment]
OK, I'll let CDOS know, and close this issue when I do.

**Comment by sfsinger19103** [comment]
Per 9/11 CDOS email, CDOS wants a button allowing export of a CSV file containing the list of ballot cards.

When that button is implemented, please close this issue.

**Comment by dmzimmerman** [comment]
Is this going to be done client side or server side? Either seems feasible.

**Comment by ranweiler** [comment]
The CSV generation should be a server endpoint, which just exposes a file to download, like the reports.

**Comment by ranweiler** [comment]
The server part of this is done in #701, and the client part is captured in #272. Closing.
