### ISSUE TITLE
Only show DOS next round control when really waiting to start next round

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#633]
First round is started by "Launch Audit", but the button to start the 2nd, 3rd, etc., round doesn't do anything.

**Comment by dmzimmerman** [comment]
This is just the templates not having been filled in right, I think. But if it happened at the end of an audit, instead of at the end of a round, that's indicative of something that will be addressed as part of the new ASM updates.

**Comment by ranweiler** [comment]
We need to make sure we hide/disable that button at appropriate times. Changing the issue name.

**Comment by sfsinger19103** [comment]
In my view, a County hasn't completed an audit round until the audit board has signed off. If the audit board reviews all the ballots and then runs away to join the circus, you'll need to find a new audit board and start the round over.

**Comment by dmzimmerman** [comment]
This view agrees with the server's view - or at least, it will, once my ASM changes are done. Except for the "start over" part, because (1) there's no way to do that right now (it _is_ doable, and addable, but not necessarily trivial), and (2) there's no reason in the rules or anything we've been told why the audit board can't change mid-audit.
