### ISSUE TITLE
Rename "Audit Board Sign-In" and "Audit" on upper right menu?

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#642]
Depending on the state, what is now called the "Audit Board Sign-In" screen (in menus, and in titles) is more of an "Audit Board Status" screen. Should it be renamed? Perhaps to "Audit Board"?

The County "Audit" item on the upper-left-corner menu has the opposite problem -- not specific enough. Maybe rename it "Ballot Card Review"?

**Comment by ranweiler** [comment]
> Depending on the state, what is now called the "Audit Board Sign-In" screen (in menus, and in titles) is more of an "Audit Board Status" screen. Should it be renamed? Perhaps to "Audit Board"?

This makes sense to me (I'd go with just "Audit Board"). We could even consider putting ithat form directly on the county dashboard, so that dashboard has 4 quadrants. That would make sign-in/sign-out really easy to do, easy to see when it _needs_ to be done, and avoids the fact that the audit board page feels a little hidden right now.

> The County "Audit" item on the upper-left-corner menu has the opposite problem -- not specific enough. Maybe rename it "Ballot Card Review"?

I disagree with this one. We really do several things in the "Audit" page besides review cards: we get the list of ballots to audit, record an interpretation of a ballot card, **review** that interpretation, submit it, and when the round is over, sign off on the round. It is truly the entire audit workflow, so I think talking about ballot cards might be confusing. But, I also think this is the sort of thing where we'd want actual user feedback and testing.

**Comment by sfsinger19103** [comment]
CDOS 9/11: use "Audit Board" and "Audit" in the County navigation menu.

**Comment by sfsinger19103** [comment]
CDOS 9/11: 

F&F Q:	The Audit Board Sign In page could be omitted, with the information/form currently on that page shown instead as a panel on the County Home Page. Is this change of interest to CDOS?

CDOS A: No, but the navigation from the Audit Board Sign In page to the Audit page could be made easier by adding a “Start Audit” button. Currently, the county navigation menu at the top needs to be used and that is not intuitive. The “Start Audit” button is shown on the “Home” page and most of the time the county will not use that button.
