### ISSUE TITLE
Change text above contest-comment box to include write-in candidates

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#661]
Instead of #591 , for the Nov 2017 version it suffices to instruct Audit Board to enter any write-in candidate info (including qualified vs. unqualified) in the comment box.

(pending confirmation from CDOS after 9/6 conversation Dwight & Stephanie)

**Comment by sfsinger19103** [comment]
CDOS 9/11: 

We need to research this situation further. We will discuss with Dominion tomorrow and provide you with feedback ASAP.

**Comment by dmzimmerman** [comment]
In theory, it is possible for the server to explicitly flag candidates as qualified write-ins if they appear after the "Write-in" column in the CVR export... but such flagging would require both database changes and parser changes, not to mention the client-side UI for dealing with that data, and we should only do it in the immediate term if we really need to.

**Comment by ranweiler** [comment]
IIUC, based on convo w/@nealmcb, any _qualified_ write-in (someone who can actually win the contest) _is_ already being displayed. The real problems are (1) cosmetic, they aren't flagged/visually offset as write-ins, so it'd be confusing that they aren't on the physical ballot card, (2) we need 100% confirmation from other vendors that we will never somehow miss a qualified write-in by depending on the CSV. More distantly, (3) for the sake of nice bookkeeping, it would be great if we had a place for unqualified write-ins _separate_ from general comments.

**Comment by sfsinger19103** [comment]
For this deliverable (per SS email to CDOS 9/14):

List all candidates present in the CVR. Do not list "Write-in" as a candidate.

As we have not heard back from CDOS about explanatory text, don't change any text.

**Comment by dmzimmerman** [comment]
Hmm. I'd somehow missed the "Do not list Write-in as a candidate" part of that email. That requires a parser change (and not a trivial one at that, since the column doesn't go away and we still have to track it).

**Comment by dmzimmerman** [comment]
Or, alternatively, a client change to simply not list any candidate called "Write-in".

**Comment by nealmcb** [comment]
Re: https://github.com/FreeAndFair/ColoradoRLA/issues/661#issuecomment-329690743 - 
 * See https://github.com/FreeAndFair/ColoradoRLA/issues/597#issuecomment-329601220  for how the audit board can handle case (2) where a candidate is missing from a contest (whether a write-in or not).
 * It's questionable whether (3) would be desirable, since we don't want to waste audit board time on transcribing frivolous write-ins. Unqualified write-ins are simply undervotes from an RLA auditing perspective.

**Comment by kiniry** [comment]
I'm including a recommendation in Weekly Report #11 on this issue.

**Comment by ranweiler** [comment]
CDOS has agreed with our recommendation that there is no need to capture info about "unqualified" write-in candidates in the comment box, since that info is extraneous to the RLA. By CO law, _unqualified_ write-ins cannot win an election, and for an RLA, they simply count as an undervote. Qualified write-ins, which _can_ win an election, are included in the CVR, and thus are already displayed as radio button options in the ballot card verification page. Closing.
