### ISSUE TITLE
ensure cookie use is secure

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#669]
We need to double-check that the cookie library we use is properly configured to ensure that session information is securely stored (HttpOnly, Secure, and SameSite, e.g.).

**Comment by ranweiler** [comment]
Our cookie usage is not currently secure. Fixing this is straightforward.

1. On the client, do not in any way use the session cookie via JS. Log the user out only when any HTTP request fails due to an authentication error.
2. On the server, enable `Secure` and `SameSite=Strict` in the `Set-Cookie` header when in production mode. In all cases, enable `HttpOnly`.

**Comment by ranweiler** [comment]
This is now done, fully on the client-side, partially on the server. We now set `HttpOnly` for cookies in all circumstances. We still need to parameterize the server config so in prod it uses `SameSite=Strict` and `Secure`, and doesn't in dev.

**Comment by ranweiler** [comment]
Closing this, as I've broken it up into the actionable #680 and #681.
