### ISSUE TITLE
Election Type in Intermediate Audit Report title shd match SoS Audit Def page

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#698]
> State   Audit Report
> --
> Generated   2017-09-13T16:36:42.224
> coordinated - 2017-11-07

Instead of "coordinated" this should read "Coordinated Election" (etc., using strings from http://localhost:3000/sos/audit).

**Comment by dmzimmerman** [comment]
The server cannot do that unless it is actually _sent_ the string "Coordinated Election" by the client, as it has no idea what those strings are; they're just strings.

**Comment by sfsinger19103** [comment]
Where are these strings stored? Not sure what you mean by "submitted" -- aren't they somehow hard-coded into the system? They show up the same way in the client every time.

**Comment by dmzimmerman** [comment]
The client submits audit information, including the election type as a string. I store that string in the database (you can see it in the `dos_dashboard` table). They are hard coded in the client, not the server.

**Comment by ranweiler** [comment]
@dmzimmerman, I'm using simple (typechecked) string enums to indicate the various election types, then presenting them in the UI using a function which sends ```electionType => `${capitalize(electionType)} Election```. I suggest doing that in the server when generating the reports.

**Comment by dmzimmerman** [comment]
Would it not make sense to simply send the display string to the server, so I can save it as-is? Adding new enums and such to the server for this doesn't make a lot of sense to me given that it's likely to change a lot for different states, etc.

**Comment by dmzimmerman** [comment]
Or are you just suggesting that I capitalize the first letter and tack " Election" onto it? That's easy enough to do, but doesn't seem very robust.

**Comment by sfsinger19103** [comment]
CDOS has asked F&F specifically to remedy this (per RLA Tool Feedback #1_tool version2)

**Comment by nealmcb** [comment]
Offhand, it would seem better to put the logic in one place, and have the client specify in what it sends exactly what string should be displayed. But the server would as usual need to ensure that that string doesn't cause any security issues.

**Comment by dmzimmerman** [comment]
It is impossible for such a string to cause security issues because it it sanitized by Hibernate before it ever touches the database.

**Comment by ranweiler** [comment]
@dmzimmerman my reasoning is that in general, I want the data that indicates the election type to be distinct from the presentation, since the presentation may change. If I change the serialization of this type in the JSON payload to be something that looks right if you pass-through write it to Excel, then that's also the representation I'll get back, so I'll have to deserialize as well. Not the end of the world, but that logic does need to happen somewhere (if we want that decoupling).

However, I also don't think the client should be the source of truth on something like a known enum. IMO, the best solution is for the server to have a type (like we do on the client) that enumerates the possible election types, and then has pretty-printed string representation wherever needed. That way, if a misbehaving client sends nonsense, the server can reject it.

**Comment by dmzimmerman** [comment]
OK. What I'll do for now is the same thing you're doing for presentation, and we can figure out a enumeration of possible election types later.
