### ISSUE TITLE
Remove audit_sequence_number from csv list of ballot cards to audit

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#753]
CDOS requested in RLA Tool Feedback #1_tool version2.

**Comment by sfsinger19103** [comment]
Addressed in #752

**Comment by nealmcb** [comment]
For the future, for verification of the audit as discussed in #601, providing a convenient means of downloading the `audit_sequence_number` along with the other information provided here is a good idea. For now, it can be obtained in the less-convenient JSON format.  But making the inclusion of the `audit_sequence_number` column depend on a query parameter would be another possible approach.

**Comment by dmzimmerman** [comment]
This issue is not closed until #752 is merged, at which point it will be closed automatically.

**Comment by dmzimmerman** [comment]
@nealmcb, the `audit_sequence_number` in the CSV only represents the actual index in the random sequence if the sequence is downloaded with duplicates and audited ballots, starting at index 0. It may be more reasonable to have a query parameter to explicitly give the full random sequence so far rather than depending on that fragile combination of parameters.
