### ISSUE TITLE
Imprinted_id format in csv & Excel downloads

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#783]
The imprinted_id in the csv download and Excel download is displayed as a date instead of a [device ID]-[batch]-[position] format.

From RLA Tool Feedback #1_tool version3.docx

**Comment by sfsinger19103** [comment]
Imprinted ID still shows as a date, not with dashes 

<img width="798" alt="imprintedid" src="https://user-images.githubusercontent.com/14353822/31189261-8e280cb4-a8ec-11e7-828a-a10d2bfe23db.png">

**Comment by sfsinger19103** [comment]
Also in the audit board's downloaded list of ballot cards to assemble, even in the raw CSV the imprinted ID looks like a date -- in the twenty-first century, no less.

<img width="569" alt="in_text_editor" src="https://user-images.githubusercontent.com/14353822/31260358-134fdc1c-aa02-11e7-986a-432ab88890fb.png">

**Comment by dmzimmerman** [comment]
I continue to believe that this is fixed. Unfortunately, Excel’s defaults are unconscionably stupid, and they treat anything that looks even remotely like a date as a date unless you say otherwise explicitly - which we do in the Excel files since PR #787 , and I just double-checked it. But if you load a CSV into Excel (and maybe into other things), it treats date-like strings as dates.

For the CSV, this is the output I just got from running the smoketest script with the following commands `./smoketest.sh; ./main.py -c 3 -E "/cvr-to-audit-download?round=1&include_audited"`:

```
<Response [200]> POST /auth-county-admin
<Response [200]> GET /cvr-to-audit-download?round=1&include_audited
<Response [200]> GET /cvr-to-audit-download?round=1&include_audited "scanner_id","batch_id","record_id","imprinted_id","ballot_type","storage_location","cvr_number","audited"
3,800,20,"3-800-20","60","Bin 1",20,"Yes"
4,1200,3,"4-1200-3","27","Bin 1",43,"Yes"
4,1200,14,"4-1200-14","32","Bin 1",53,"Yes"
4,1200,35,"4-1200-35","44","Bin 1",73,"Yes"
9,3200,11,"9-3200-11","7","Bin 17",99,"Yes"
10,2,4,"10-2-4","4","Bin 22",144,"Yes"
10,2,16,"10-2-16","1","Bin 22",156,"Yes"
```

There is nothing in there that looks like a date. I'm not sure what you used  to acquire your "raw" output above, but I don't think it was really raw output, unless something very bizarre is happening with the particular CVR set you're using.

**Comment by sfsinger19103** [comment]
You're right -- I can't reproduce the error. 
<img width="636" alt="new_in_textedit" src="https://user-images.githubusercontent.com/14353822/31263112-ed616f94-aa14-11e7-9616-7ea2537ad4f7.png">

**Comment by nealmcb** [comment]
The inability to disable this misfeature in Microsoft Excel is so pervasive that it has led biologists to rename genes with names like `MARCH1` or `SEPT1`, after seeing that the data in hundreds of scientific papers was corrupted.

See: [Scientists rename human genes to stop Microsoft Excel from misreading them as dates \- The Verge](https://www.theverge.com/2020/8/6/21355674/human-genes-rename-microsoft-excel-misreading-dates)

Excerpts:

> There’s no easy fix, either. Excel doesn’t offer the option to turn off this auto-formatting, and the only way to avoid it is to change the data type for individual columns. Even then, a scientist might fix their own data, but as soon as someone else opens the same spreadsheet in Excel without thinking, errors will be introduced all over again.

> ... From now on, they say, human genes and the proteins they expressed will be named with one eye on Excel’s auto-formatting. That means the symbol MARCH1 has now become MARCHF1, while SEPT1 has become SEPTIN1, and so on. A record of old symbols and names will be stored by HGNC to avoid confusion in the future.

> So far, the names of some 27 genes have been changed like this over the past year

Who knows how many other situations, in how many other fields of endeavor, there are out there.

Please, Microsoft, just let people disable this confusing rewriting of our data!
