### ISSUE TITLE
Add contest name, risk limit, random seed to audit report

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#785]
6.     The audited contest name, the risk limit, and the random seed do not appear on the audit report Excel spreadsheet. These items should be documented as part of the audit record. 

from RLA Tool Feedback #1_tool version3.docx

**Comment by dmzimmerman** [comment]
I'm not at all sure what they want here. What is the "audited contest name", in this case, and where do they think it should appear? There is an explicit list of "audited contests" in both the county report and, on a county-by-county basis, in the DoS report.

**Comment by sfsinger19103** [comment]
Waiting for answer from CDOS to this question (emailed by SS 10/3):

We can list audited contests on the individual County pages in the Audit Report available on the Secretary of State dashboard. Which would you like:
-A list looking exactly like the list on the Summary page (but with only that one County's contests listed)? 
-A list of contest names, without any other columns?

**Comment by sfsinger19103** [comment]
While we're waiting for CDOS response, let's implement the first option: 

A list looking exactly like the list on the Summary page (but with only that one County's contests listed) on each County page in the SoS report.

**Comment by sfsinger19103** [comment]
NB: risk limit and random seed have been incorporated in the report, so the only open item is the names of the audited contests.

**Comment by dmzimmerman** [comment]
I don't think we should implement the first option before getting their response, because their previous response indicated that what they really wanted was something that the first option would not give them, and my sense is that having the contest _names_ is not really what they wanted at all except insofar as we could list per-contest discrepancy totals (note that the "desired outcome" they sent us didn't have contest names on it at all).

**Comment by sfsinger19103** [comment]
No response received from CDOS, so audited contest names will be on summary sheet but not on other sheets.
