### ISSUE TITLE
analyze DB choices

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#87]
We need to reflect upon input from CDOS and make a recommendation to them in our next weekly report.

**Comment by dmzimmerman** [comment]
We did not actually make a recommendation in the weekly report, but we have settled on Postgres with streaming replication for redundancy. Note that this means a single database server is used by the system at a time, and another (or more than one other) is available for failover, rather than a set of distributed servers being used interchangeably - which seems perfectly reasonable in the deployment environments we're considering.

**Comment by kiniry** [comment]
I'm closing this ticket as we are making this recommendation explicit in our next weekly report, per earlier messages to @sfsinger19103.
